import type { Metadata } from "next";
import { Sora } from "next/font/google";
import { Nav } from "./components/Nav";
import { Header } from "./components/Header";
import { AnimatePresence, motion } from "framer-motion";
import { useRouter } from "next/router";
import { Transtition } from "./components/Transition";

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const router = useRouter();
  return (
    <html lang="en">
      <AnimatePresence mode="wait">
      <motion.div key={router.route}>
      <Transtition/>
      <Nav />
      <Header />
      <body className={sora.className}>{children}</body>
      </motion.div>
      </AnimatePresence>
    </html>
  );
}
